Create ko.rs
rustdesk/rustdesk pull request #1271
Opened 2022-08-14 05:07 UTC by kordood

Add UI Language Korean
Signed-off-by: kordood <gigacms@gmail.com>

2022-08-14 07:19 UTC, rustdesk commented
Thanks, you need to modify lang.rs also.

2022-08-16 01:58 UTC, kordood commented
Great, I updated the lang.rs.

2022-08-16 02:01 UTC, rustdesk requested changes

2022-08-16 02:01 UTC, rustdesk commented on src/lang.rs
> +        "ja" => ko::T.deref(),
Wrong here, :)

2022-08-16 05:50 UTC, kordood commented on src/lang.rs
> +        "ja" => ko::T.deref(),
Oops! Thank you for finding it :D

2022-08-16 06:31 UTC, merged