Windows key input bug
rustdesk/rustdesk pull request #1857
Opened 2022-10-28 11:50 UTC by sj6219

It works abnormally when you connect to the window server and type shift + left arrow.
It's been modified, so please refer to it.

2022-10-28 12:41 UTC, rustdesk commented
@asur4s please help review

2022-10-29 04:37 UTC, asur4s requested changes

2022-10-29 04:37 UTC, asur4s commented on src/server/input_service.rs
> +        //let key = rdev::windows::keycodes::key_from_code(code);
Remove it.

2022-10-29 04:37 UTC, asur4s commented on src/server/input_service.rs
> +    let click_numlock = {
It looks good, it would be even better if it could be written in the sync_status function

2022-10-29 05:53 UTC, sj6219 commented
I modified it.

2022-10-29 05:53 UTC, asur4s approved these changes

2022-10-29 05:53 UTC, asur4s commented
LGTM

2022-10-29 07:17 UTC, rustdesk commented
Thanks @sj6219  @asur4s

2022-10-29 07:17 UTC, merged