Warn on MIT-SHM not working on Linux X11
rustdesk/rustdesk pull request #6856
Opened 2024-01-12 09:13 UTC by wesley800

This PR simply throws a warn into log, when rustdesk server runs on an Linux box with its X11 server having MIT-SHM set to disabled. Plus another minor fix on pointer usage.
Personally I'm very unsatisfied about the current way of passing MIT-SHM errors from `scrap` to the server. Need some hint on API designing flavors.

2024-01-12 09:22 UTC, rustdesk commented
This fixes bug or adds feature?

2024-01-12 09:31 UTC, wesley800 commented
> This fixes bug or adds feature?

I believe it's a feature, but only for debugging.

2024-01-12 09:32 UTC, rustdesk commented
Debug for what?

2024-01-12 09:42 UTC, wesley800 commented
Currently when rustdesk runs server on SHM disabled environment, the client only sees black screen after connecting to the server, while keyboard and mouse works as normal. It is at least to me very confusing, when there's no relevant lines in rustdesk's log.
I tried to minimize the change. It also sounds reasonable to me to just throw a fatal error, cuz `scrap` requires SHM explicitly.

2024-01-12 09:53 UTC, rustdesk commented
It is better to show here.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/f74a37a1-363a-45e8-a6b7-06ac0727d169)

https://github.com/rustdesk/rustdesk/blob/286181ca04c43455ccf183badcf418cc9edbc231/flutter/lib/desktop/pages/desktop_home_page.dart#L324

2024-01-12 09:58 UTC, wesley800 commented
I agree to add a warn on GUI interface. What about headless setup? And I'm sorry that I can't write in flutter...

2024-01-15 08:09 UTC, rustdesk requested changes

2024-01-15 08:09 UTC, rustdesk commented on src/server/video_service.rs
> +        if let Err(err) = inner.get_shm_status() {
I do not think this can be compiled on non-Linux.

2024-01-20 13:19 UTC, wesley800 commented
Could you explain a bit on why it's closed?

2024-01-21 07:05 UTC, rustdesk commented
You did not answer https://github.com/rustdesk/rustdesk/pull/6856#discussion_r1452037313. I thought I had given up.

2024-01-21 16:27 UTC, wesley800 commented
I was expecting for ideas on how to pass the warns around, rather than a small `#[cfg]` modification. As I stated I have a strong feel that the PR needs refactor. Current commits are just for quick illustration and proof.

To be more specific, would you mind changing API of `scrap`? e.g. let `Capturer::new` returns `Result<(Capturer,WarningKind),ErrorKind>`, rather than `Result<Capturer,ErrorKind>`?

If API changing is not preferred, would you prefer the state (`shm_status` field) to be stored in `Server` instance, or checks on the fly each time `get_shm_status` is called?

2024-01-22 08:46 UTC, rustdesk commented
I prefer `#[cfg]`

2024-01-24 12:56 UTC, wesley800 commented
BTW I'll try to add a tooltip to GUI, but it will take some time.

2024-01-24 13:02 UTC, rustdesk commented
👍

2024-01-24 13:48 UTC, 109-999 commented
👍

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: RustDesk ***@***.***>
Sent: Wednesday, January 24, 2024 6:47:26 PM
To: rustdesk/rustdesk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [rustdesk/rustdesk] Warn on MIT-SHM not working on Linux X11 (PR #6856)


👍

—
Reply to this email directly, view it on GitHub<https://github.com/rustdesk/rustdesk/pull/6856#issuecomment-1908080242>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BEP5XLQAAL24FF5ABXRQ76LYQEA6FAVCNFSM6AAAAABBXZXZWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBYGA4DAMRUGI>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-01-31 09:49 UTC, merged