Fix: Mac retina display video blur
rustdesk/rustdesk pull request #6980
Opened 2024-01-24 16:44 UTC by sahilyeole

Fixes: #5246 
Working: https://github.com/rustdesk/rustdesk/issues/5246#issuecomment-1907200031

`BackingScaleFactor` is 2.0 if it is a retina display. [Doc](https://developer.apple.com/documentation/appkit/nswindow/1419459-backingscalefactor)

2024-01-26 03:07 UTC, rustdesk requested changes

2024-01-26 03:07 UTC, rustdesk commented on libs/scrap/src/quartz/display.rs
> +        unsafe { BackingScaleFactor() == 2.0 }
It can not be 1.5, 2.5, 3?

2024-01-26 03:07 UTC, rustdesk commented on libs/scrap/src/quartz/display.rs
> +        unsafe { BackingScaleFactor() == 2.0 }
Why not use > 1.0?

2024-01-26 03:07 UTC, rustdesk commented on libs/scrap/src/quartz/display.rs
> +            h * 2
Why not use BackingScaleFactor directly?

2024-01-26 04:50 UTC, merged

2024-01-26 11:16 UTC, zhangbo8418 commented
This will cause the mouse pointer to not hit the correct location. . .

2024-01-26 11:19 UTC, rustdesk commented
Revert for the time being

2024-01-26 11:35 UTC, rustdesk commented
@sahilyeole we will take care of this, because it is a little complex now.

2024-02-21 14:27 UTC, rustdesk commented
@21pages follow this up, let's translate the mouse event x/y in connection.rs when receiving mouse event.

2024-02-22 03:59 UTC, 21pages commented
@zhangbo8418 Could you try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-retina.dmg ?