http/https proxy
rustdesk/rustdesk pull request #7600
Opened 2024-04-03 16:09 UTC by yuluo-zy

Add http and https proxy functions, and establish remote proxy server access by filling in the relevant http and https addresses.

for example： “http://192.168.1.3:12345” "https://192.168.1.3:443"

Also supports user authentication。

Fixes #7487 #5687

2024-04-03 16:29 UTC, rustdesk commented
Please use tls-native for macos and windows only, the others use rustls.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/5b3f38b4-d9d8-47b7-9f83-1d758ce700b2)

2024-04-03 16:31 UTC, rustdesk commented
@fufesou please review the others.

2024-04-04 03:01 UTC, fufesou commented
![image](https://github.com/rustdesk/rustdesk/assets/13586388/f35666d1-9f3e-4ff9-8c1c-6f8e708db4b1)

Two bugs here  https://github.com/rustdesk/rustdesk/blob/129548764e28eee6e2921c0c770fb83b7e16621f/libs/hbb_common/src/socket_client.rs#L52
1. Problem with original code. If detecting the address of a proxy, it should detect the address directly instead of using a proxy. 
2. When checking http or https or some other schema the host should be extracted.

2024-04-04 03:26 UTC, fufesou commented
Please add tooltip it's default socks5, http or https.

![image](https://github.com/rustdesk/rustdesk/assets/13586388/09e9f753-b85d-4674-b0de-78e119e9f811)

2024-04-04 04:20 UTC, fufesou commented
I can see http request on rust side is using the proxy. But the request on flutter side does not.

https://github.com/rustdesk/rustdesk/blob/129548764e28eee6e2921c0c770fb83b7e16621f/flutter/lib/models/user_model.dart#L41

TODO: socks5 support on http request.

2024-04-05 14:57 UTC, yuluo-zy commented
> 我可以看到 Rust 端的 http 请求正在使用代理。但 flutter 端的请求却没有。
> 
> https://github.com/rustdesk/rustdesk/blob/129548764e28eee6e2921c0c770fb83b7e16621f/flutter/lib/models/user_model.dart#L41
> 
> 通过搜索可以找到flutter端所有的http请求`mainGetApiServer()`
> 
> ====更新====
> 
> 我看不到 rust http 请求在哪里设置了代理。您还应该在 Rust 端设置代理。
> 
> TODO：socks5 支持 http 请求。

Sorry, I only reviewed the code mentioned here https://github.com/rustdesk/rustdesk/discussions/5687#discussioncomment-6996866. For the above content, do I need to add a global http interceptor to complete it, including flutter and rust content?

2024-04-05 14:59 UTC, yuluo-zy commented
> ![image](https://private-user-images.githubusercontent.com/13586388/319425372-f35666d1-9f3e-4ff9-8c1c-6f8e708db4b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjg2MDgsIm5iZiI6MTcxMjMyODMwOCwicGF0aCI6Ii8xMzU4NjM4OC8zMTk0MjUzNzItZjM1NjY2ZDEtOWYzZS00ZmY5LThjMWMtNmY4ZTcwOGRiNGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE0NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZGVmOGVjZGJmNWMyMDgyNzQzMjM3NGE0NGNjNWQ4Mjk3MDUyZmIzNjYzYWU2Y2MwYTJlODMzYzc2MDFlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEAJAcQXFPn37ogMTtnNgY1wyI6PXFrlhTXuboVXHjU)
> 
> Two bugs here
> 
> https://github.com/rustdesk/rustdesk/blob/129548764e28eee6e2921c0c770fb83b7e16621f/libs/hbb_common/src/socket_client.rs#L52
> 
> 1. Bug in the original code. If detecting the address of a proxy, it should detect the address directly instead of using a proxy.
> 2. When checking http or https or some other schema the host should be extracted.

Sorry, I will improve this code

2024-04-05 15:09 UTC, yuluo-zy commented
> Please use tls-native for macos and windows only, the others use rustls.
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/319271457-5b3f38b4-d9d8-47b7-9f83-1d758ce700b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjg2MDgsIm5iZiI6MTcxMjMyODMwOCwicGF0aCI6Ii83MTYzNjE5MS8zMTkyNzE0NTctNWIzZjM4YjQtZDlkOC00N2I3LTlmODMtMWQ3NThjZTcwMGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE0NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZDE4Y2U4NTg1N2NhNDU4NWM2ZTJkNjU2N2NkZGJjZDM2ZTRmNDQwZGI0NTk5NWNjMzBhYzE3ZTk0ZWQ3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjzUqzpyTOrGawktkl5ttCIwwnL4evvt90pz3BD2fiM)
I tested on ubuntu18 and there is no problem with tokio-native-tls. Is rustls used here to support Android and ios? I checked the relevant front-end code rustdesk/flutter/lib/mobile, and there is no proxy setting.

2024-04-05 15:10 UTC, fufesou commented
> Sorry, I only reviewed the code mentioned here https://github.com/rustdesk/rustdesk/discussions/5687#discussioncomment-6996866. For the above content, do I need to add a global http interceptor to complete it, including flutter and rust content?

Sounds ok, but please make sure the global http interceptor  only affect current process.

For Socks5, it was implemented very early. There seemed to be no http requests at that time, so it is currently missing. If it is convenient, please add it. If it's inconvenient, forget it.

2024-04-05 15:17 UTC, yuluo-zy commented
> test_if_valid_server

Thank you for your reply. Regarding the proxy issue of http requests, I will review the relevant code and propose a specific solution.
But for this PR, it currently seems to have no impact on the access and remote control of the console (except for the test_if_valid_server function above, which I did forget to modify)

> > 抱歉，我只查看了上面提到的代码[#5687（评论）](https://github.com/rustdesk/rustdesk/discussions/5687#discussioncomment-6996866)。对于上面的内容，我是否需要添加一个全局的http拦截器来完成，包括flutter和rust的内容？
> 
> 听起来不错，但请确保全局http拦截器只影响当前进度。
> 
> 对于Socks5来说，很早就实现了。当时好像没有http请求，所以目前是解除的。如果方便的话请补充一下。如果不方便的话，就忘了吧。

2024-04-05 15:20 UTC, yuluo-zy commented
> > Sorry, I only reviewed the code mentioned here [#5687 (comment)](https://github.com/rustdesk/rustdesk/discussions/5687#discussioncomment-6996866). For the above content, do I need to add a global http interceptor to complete it, including flutter and rust content?
> 
> Sounds ok, but please make sure the global http interceptor only affect current process.
> 
> For Socks5, it was implemented very early. There seemed to be no http requests at that time, so it is currently missing. If it is convenient, please add it. If it's inconvenient, forget it.

Thank you for your reply. Regarding the proxy issue of http requests, I will review the relevant code and propose a specific solution.
But for this PR, it currently seems to have no impact on the access and remote control of the console (except for the test_if_valid_server function above, which I did forget to modify)

2024-04-06 07:26 UTC, rustdesk commented
> > Please use tls-native for macos and windows only, the others use rustls.
> > ![image](https://private-user-images.githubusercontent.com/71636191/319271457-5b3f38b4-d9d8-47b7-9f83-1d758ce700b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjg2MDgsIm5iZiI6MTcxMjMyODMwOCwicGF0aCI6Ii83MTYzNjE5MS8zMTkyNzE0NTctNWIzZjM4YjQtZDlkOC00N2I3LTlmODMtMWQ3NThjZTcwMGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE0NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZDE4Y2U4NTg1N2NhNDU4NWM2ZTJkNjU2N2NkZGJjZDM2ZTRmNDQwZGI0NTk5NWNjMzBhYzE3ZTk0ZWQ3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjzUqzpyTOrGawktkl5ttCIwwnL4evvt90pz3BD2fiM)
> > I tested on ubuntu18 and there is no problem with tokio-native-tls. Is rustls used here to support Android and ios? I checked the relevant front-end code rustdesk/flutter/lib/mobile, and there is no proxy setting.

Ubuntu 18, Ubuntu 20, 22 has different ssl version, but RustDesk only have one version, so We do not use native tls on Linux.

2024-04-07 14:45 UTC, yuluo-zy commented
> I can see http request on rust side is using the proxy. But the request on flutter side does not.
> 
> https://github.com/rustdesk/rustdesk/blob/129548764e28eee6e2921c0c770fb83b7e16621f/flutter/lib/models/user_model.dart#L41
> 
> You can find the all http requests on the flutter side by searching `mainGetApiServer()`
> 
> ==== update ====
> 
> I cann't see where rust http requests have set the proxy. You should also set the proxy on rust side.
> 
> TODO: socks5 support on http request.
For the Rust side code that handles HTTP request proxying, I see that it's implemented using `reqwest` within the `/src/hbbs_http` module. I noticed that within the plugin, `request_plugin_sign` involves HTTP usage. Do these areas need to be modified? Are there any other places that I may have missed?

2024-04-07 14:50 UTC, rustdesk commented
Yes, rust side uses reqwest for http, reqwest support socks/http/https proxy very well. But the dart pub http does not support proxy well. I hope we can replace http pub with native reqwest via ffi.

2024-04-07 14:54 UTC, yuluo-zy commented
> Yes, rust side uses reqwest for http, reqwest support socks/http/https proxy quite well. But the dart pub http does not support proxy well. I hope we can replace http pub with native reqwest via ffi.

Do you mean that you want me to modify all HTTP requests on the Flutter side to be done through FFI by using Rust's reqwest library?

2024-04-07 14:58 UTC, rustdesk commented
Exactly, yes.

2024-04-07 15:00 UTC, rustdesk commented
Oh, sorry, you do not have to do this, it is just my expectation since you mentioned. :)

2024-04-07 15:30 UTC, rustdesk commented
Thanks, you are right, another PR is better.

2024-04-13 05:33 UTC, rustdesk requested changes

2024-04-13 05:33 UTC, rustdesk commented on libs/hbb_common/src/tcp.rs
> +    pub(crate)SocketAddr,
I guess you did not format files. `pub(crate) Framed` vs `pub(crate)SocketAddr`

2024-04-13 05:33 UTC, rustdesk commented on src/rendezvous_mediator.rs
> +use hbb_common::log::info;
Please follow our `use` style. (grouped)

2024-04-13 05:33 UTC, rustdesk commented on libs/hbb_common/Cargo.toml
> +base64 = "0.22"
`rustdesk/Cargo.toml` has base64 also, could you change to use `hbb_common::base64` in `rustdesk/src`?

2024-04-13 05:33 UTC, rustdesk commented on libs/hbb_common/Cargo.toml
> +webpki-roots = "0.26"
rustls-native-certs is better, or even https://github.com/rustls/rustls-platform-verifier.

Could you please help check if reqwest can use 'rustls-platform-verifier"? Currently, we use rustls-native-certs feature for rustls of reqwest in rustdesk/Cargo.toml.

2024-04-13 05:33 UTC, rustdesk commented on libs/hbb_common/Cargo.toml
> +webpki-roots = "0.26"
webpki-roots also recommend rustls-platform-verifie, https://github.com/rustls/webpki-roots?tab=readme-ov-file#:~:text=rustls%2Dplatform%2Dverifier

2024-04-13 06:52 UTC, yuluo-zy commented on libs/hbb_common/Cargo.toml
> +webpki-roots = "0.26"
I haven't finished editing yet. Sorry, I forgot to set the draft status. (´ﾟдﾟ`)

2024-04-13 06:55 UTC, yuluo-zy commented on libs/hbb_common/Cargo.toml
> +webpki-roots = "0.26"
Yes, I will make modifications according to the issues you pointed out. (´///☁///`)

2024-04-16 03:22 UTC, yuluo-zy commented
> > Yes, rust side uses reqwest for http, reqwest support socks/http/https proxy quite well. But the dart pub http does not support proxy well. I hope we can replace http pub with native reqwest via ffi.
> 
> Do you mean that you want me to modify all HTTP requests on the Flutter side to be done through FFI by using Rust's reqwest library?

https://github.com/rustdesk/rustdesk/blob/1d4c129e9c286f4e2bb866b1629788b6aa2ecabe/src/ui_interface.rs#L712


I noticed that Rust has an existing function for making POST requests. Can I use this function to perform FFI calls? However, it seems that the result would require constant callback queries to check the outcome.

2024-04-16 03:24 UTC, rustdesk commented
Yes, you can

2024-04-16 17:59 UTC, yuluo-zy commented
> Yes, you can

I encountered a rather awkward problem when testing Flutter's HTTP requests through FFI by calling a Rust HTTP client for verification. I discovered that the domain https://admin.rustdesk.com does not exist. Under these circumstances, how should I proceed with functional testing, especially since the related features require the support of RUSTDESK SERVER PRO?

2024-04-17 02:29 UTC, rustdesk commented
@21pages will give you a test server

Please have a good wrapper of the http.post in dart. To make sure minimun impact, please still use http pub when no proxy, and only use native ffi post for proxy.

2024-04-17 02:38 UTC, 21pages commented
@yuluo-zy please contact me with email cGFnZXMyMUAxNjMuY29t (base64)

2024-04-23 06:43 UTC, rustdesk commented
Good job

2024-04-23 07:00 UTC, merged

2024-04-23 07:11 UTC, rustdesk commented
A lot of CI failures, https://github.com/rustdesk/rustdesk/actions/runs/8796163902/job/24138522662

2024-04-23 07:13 UTC, yuluo-zy commented
> A lot of CI failures, https://github.com/rustdesk/rustdesk/actions/runs/8796163902/job/24138522662

I'm sorry, I'm fixing these issues today,

2024-04-23 07:26 UTC, rustdesk commented
Reverted

2024-04-25 03:09 UTC, rustdesk commented
@yuluo-zy ?

2024-04-25 03:15 UTC, yuluo-zy commented
Hello, this ci process has been waiting for the application of the mac-arm platform test, the other builds have been passed, do I apply for the merge now, or do I wait for the ci to be fully completed? @rustdesk 

https://github.com/yuluo-zy/rustdesk/actions/runs/8811459353